branches:
  - main
  - name: beta
    prerelease: true
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: eslint
  - - '@semantic-release/release-notes-generator'
    - preset: eslint
  - - '@semantic-release/npm'
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "chmod +x ./.release-scripts/*.sh && ./.release-scripts/verify-conditions.sh"
      prepareCmd: "VERSION=${nextRelease.version} ./.release-scripts/prepare.sh"
      publishCmd: "VERSION=${nextRelease.version} CHANNEL=${nextRelease.channel} ./.release-scripts/publish.sh"
  - - '@semantic-release/github'
    - successComment: "This ${issue.pull_request ? 'pull request is included' : 'issue is resolved'} in version [${nextRelease.version}](<github_release_url>)"
      releasedLabels: [ "released<%= nextRelease.channel ? ` in ${nextRelease.channel}` : '' %>" ]
      assignees:
      - jftanner
