openapi: 3.0.0

info:
  version: Unreleased
  title: Silence Among Us
  description: |
    Discord channel manager for Among Us.

  contact:
    name: Github Repository
    url: https://github.com/tanndev/silence-among-us#silence-among-us

servers:
  - description: Current
    url: /api

tags:
  - name: Server Information

paths:
  /server:
    get:
      operationId: getInfo
      summary: Get info about this server
      tags: [Server Information]
      description: Get information about this server
      responses:
        '200':
          description: Details about the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    description: Version of the app.
                    example: 1.0.0
                  guildsSupported:
                    type: number
                    description: How many guilds are currently supported by the server.
                  lobbiesInProgress:
                    type: number
                    description: Number of lobbies currently in progress across all guilds.

  /server/guilds:
    get:
      operationId: getGuildsList
      summary: See all the guilds supported by this server.
      tags: [Server Information]
      description: |
        Get a list of all the guilds supported by this server.

        The returned list will only include the guild names, not their IDs or any other information.
      responses:
        '200':
          description: List of supported guilds
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: Name of a guild
                  example: Tanndev

  /server/lobbies:
    get:
      operationId: getLobbiesList
      summary: See all the lobbies currently in progress.
      tags: [Server Information]
      description: |
        Get a list of all the lobbies currently in progress.

        The returned list will only include the guild and voice channel names.
      responses:
        '200':
          description: List of supported guilds
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: Name of a guild and the channel
                  example: Tanndev - Among Us

components:
  responses:
    404NotFoundError:
      description: The requested resource wasn't found.
    4xxClientError:
      description: Something was wrong with the request.
    5xxInternalError:
      description: Something went wrong in the server.

  schemas:
    Lobby:
      type: object
      description: |
        Information about a single Discord channel being tracked as a game, along with game-state information for
        automatically muting/unmuting players.

        A lobby is built around a single Discord voice channel, and assumes that anyone joining that channel is
        playing that game. So the `voiceChannelId` is also used as a lobby id.
      required: [voiceChannelId, phase, players]
      additionalProperties: false
      properties:
        voiceChannelId:
          type: string
          description: The id of the Discord voice channel being used for the game.
        textChannelId:
          type: string
          description: The ID of the Discord text channel where updates should be posted.
        phase:
          type: string
          description: |
            The current phase of the lobby, as one of the following values:
            - `Intermission`: Between games
              - Everyone can talk.
              - New players join as living.
            - `Working`: In game, while the crew are performing tasks
              - Living players are muted and deafened.
              - Dead players are unmuted and can talk to each other.
              - Other players are muted/unmuted according to settings.
              - New players join as waiting.
            - `Meeting`: In game, during a meeting
              - Living players can talk.
              - Dead layers are muted.
              - Other players are muted/unmuted according to settings.
          enum: [intermission, working, meeting]
        players:
          type: array
          description: List of all players currently (or recently) in the channel.
          items:
            $ref: "#/components/schemas/Player"
        room:
          $ref: "#/components/schemas/Room"

    Player:
      type: object
      description: Information about a player, their current state in game, and their voice channel.
      required: [status, id]
      additionalProperties: false
      properties:
        status:
          type: string
          description: |
            The current status of the player, with one of the following values:
            - `Living`: Alive in-game, or in intermission.
            - `Dead`: Dead in-game. (Will change to `living` at next intermission.)
            - `Waiting`: Joined while a game was in progress. (Will change to `living` at next intermission.)
            - `Spectating`: Not playing the game, but still in the voice channel.
          enum: [Living, Dead, Waiting, Spectating]
        discordId:
          type: string
          description: The player's unique ID in Discord
        originalNickname:
          type: string
          description: The player's original nickname in discord, before they joined the lobby.
        amongUsName:
          type: string
          description: (Optional) The player's name in-game.
        amongUsColor:
          type: string
          description: (Optional) the player's color in-game.
          enum: [Red, Blue, Green, Pink, Orange, Yellow, Black, White, Purple, Brown, Cyan, Lime]

    Room:
      type: object
      description: (Optional) Game room in Among Us
      required: [code, region]
      additionalProperties: false
      nullable: true
      properties:
        code:
          type: string
          description: The room code of the game, for players to join.
          pattern: '^[A-Z]{6}$'
          example: ABCDEF
        region:
          type: string
          description: The region where the game is hosted.
          default: North America
          enum:
            - North America
            - Europe
            - Asia